sonar.projectKey=career-clarity
sonar.projectName=Career Clarity NextJS
sonar.sources=src
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,.next/**,**/*.test.jsx